# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvReturns <- function(levels) {
    .Call('bangwa_mvReturns', PACKAGE = 'bangwa', levels)
}

uvReturns <- function(levels) {
    .Call('bangwa_uvReturns', PACKAGE = 'bangwa', levels)
}

indexSequence <- function(length) {
    .Call('bangwa_indexSequence', PACKAGE = 'bangwa', length)
}

shuffleIndicesDestructive <- function(idx) {
    .Call('bangwa_shuffleIndicesDestructive', PACKAGE = 'bangwa', idx)
}

shuffleIndicesSafe <- function(idx) {
    .Call('bangwa_shuffleIndicesSafe', PACKAGE = 'bangwa', idx)
}

shuffleIndicesByLength <- function(length) {
    .Call('bangwa_shuffleIndicesByLength', PACKAGE = 'bangwa', length)
}

zmbdSafe <- function(target, lower, upper) {
    .Call('bangwa_zmbdSafe', PACKAGE = 'bangwa', target, lower, upper)
}

ttbdInner <- function(target, lower, upper) {
    .Call('bangwa_ttbdInner', PACKAGE = 'bangwa', target, lower, upper)
}

ttbd <- function(target, lower, upper) {
    .Call('bangwa_ttbd', PACKAGE = 'bangwa', target, lower, upper)
}

