# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvReturns <- function(levels) {
    .Call('bangwa_mvReturns', PACKAGE = 'bangwa', levels)
}

uvReturns <- function(levels) {
    .Call('bangwa_uvReturns', PACKAGE = 'bangwa', levels)
}

